# Generated by Django 3.0.5 on 2020-12-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('EmailAddress', models.CharField(max_length=50)),
                ('ContactNumber', models.IntegerField()),
                ('HomeAddress', models.TextField(default='')),
                ('Birthday', models.DateField(default='')),
                ('Nickname', models.CharField(max_length=50)),
            ],
        ),
    ]
