# Generated by Django 3.1.5 on 2021-01-12 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Birthday',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ContactNumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter in +9666666699.Upto 15 digits', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='HomeAddress',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
